version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ./club_app/
      dockerfile: ./Dockerfile

    volumes:
      # - type: volume
      #   source: db
      #   # source: /docker/data/db
      #   target: /club_app/db.sqlite3

      - type: volume
        source: static
        # source: /docker/data/static
        target: /app/static

      - type: volume
        source: socket
        target: /app/tmp/sockets/

    environment:
      - HOST=[2400:4151:4281:7300:3a71:9959:3541:9174]
    # env_file:
    #   - ./.env
    # restart: always

    depends_on:
      - nginx
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile

    ports:
      - 61232:80

    volumes:
      - type: volume
        source: static
        # source: ./nginx/static
        target: /static

      - type: volume
        source: socket
        target: /app/tmp/sockets/

  db:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE: club_app
      - MYSQL_USER: root
      - MYSQL_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
volumes:
  static:

  socket:
