version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ./club_app/
      dockerfile: ./Dockerfile

    volumes:
      - type: volume
        source: socket
        target: /app/tmp/sockets/

      - type: volume
        source: static
        target: /var/www/static/

      - type: volume
        source: media
        target: /var/www/media/

      - type: volume
        source: db
        target: /var/run/mysql/

      - type: volume
        source: db_socket
        target: /var/run/mysqld/

    environment:
      IS_PRODUCT: 'FALSE'
      HOST: 'localhost'
      IS_DOCKER: 'True'

    # restart: always

    depends_on:
      - nginx
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile

    ports:
      - 80:80

    volumes:
      - type: volume
        source: socket
        target: /app/tmp/sockets/

      - type: volume
        source: static
        target: /static/

      - type: volume
        source: media
        target: /media/

  db:
    container_name: mysql
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_DATABASE: club_app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql/

      - type: volume
        source: db_socket
        target: /var/run/mysqld/

    depends_on:
      - nginx

volumes:
  socket:
  static:
  media:
  db:
  db_socket: