# Generated by Django 4.2 on 2023-11-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDB',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendancedb',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='attend_unique'),
        ),
    ]
