# Generated by Django 4.2 on 2023-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancedb',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='attend_unique'),
        ),
    ]
