# Generated by Django 4.2 on 2023-11-21 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='点数')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_id', to='score.examdb', verbose_name='試験名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scoredb',
            constraint=models.UniqueConstraint(fields=('user', 'exam_name'), name='unique_exam'),
        ),
    ]
